defmodule Pod.Creators do
  @moduledoc """
  The Creators context.

  Handles everything around creator profiles — creation, updates, lookups,
  and follower counts. A Creator is linked one-to-one with a User account.
  Every broadcaster on the platform is a Creator.
  """

  import Ecto.Query
  alias Pod.Repo
  alias Pod.Stream.Creator

  # ---------------------------------------------------------------------------
  # Creating and updating creators
  # ---------------------------------------------------------------------------

  @doc """
  Creates a creator profile for an existing user.

  A user must have a creator profile to schedule or broadcast streams.
  The channel_id is auto-generated by the changeset — no need to pass it.
  An invite_key is generated automatically and is unique per creator.
  """
  def create_creator(attrs) do
    invite_key = generate_invite_key()
    attrs_with_key = Map.put(attrs, "invite_key", invite_key)
    IO.inspect(attrs_with_key, label: "Creating creator with attrs")
    %Creator{}
    |> Creator.changeset(attrs_with_key)
    |> Repo.insert()
  end

  @doc """
  Updates a creator's profile details — name, avatar, bio.
  """
  def update_creator(%Creator{} = creator, attrs) do
    creator
    |> Creator.update_changeset(attrs)
    |> Repo.update()
  end

  # ---------------------------------------------------------------------------
  # Fetching creators
  # ---------------------------------------------------------------------------

  @doc """
  Gets a creator by their ID.
  """
  def get_creator(id), do: Repo.get(Creator, id)

  @doc """
  Gets a creator by their ID, raising if not found.
  """
  def get_creator!(id), do: Repo.get!(Creator, id)

  @doc """
  Gets a creator by their user_id.

  Used after login to load the creator profile associated with the
  authenticated user account.
  """
  def get_creator_by_user(user_id) do
    Repo.get_by(Creator, user_id: user_id)
  end

  @doc """
  Gets a creator by their channel_id.

  channel_id is the public-facing identifier used in URLs and the RTMP path.
  e.g. rtmp://yourserver/live/{channel_id}/{stream_key}
  """
  def get_creator_by_channel(channel_id) do
    Repo.get_by(Creator, channel_id: channel_id)
  end

  @doc """
  Checks whether a user already has a creator profile.
  Used during onboarding to avoid duplicate creator records.
  """
  def creator_exists_for_user?(user_id) do
    Creator
    |> where([c], c.user_id == ^user_id)
    |> Repo.exists?()
  end

  @doc """
  Gets a creator with their live streams preloaded.
  Useful for public profile pages.
  """
  def get_creator_with_streams(id) do
    Creator
    |> where([c], c.id == ^id)
    |> preload(:live_streams)
    |> Repo.one()
  end

  # ---------------------------------------------------------------------------
  # Follower management
  # ---------------------------------------------------------------------------

  @doc """
  Increments the follower count for a creator by 1.
  Called when a user follows the creator.
  """
  def increment_followers(%Creator{} = creator) do
    creator
    |> Creator.update_changeset(%{follower_count: creator.follower_count + 1})
    |> Repo.update()
  end

  @doc """
  Decrements the follower count for a creator by 1.
  Guards against going below zero.
  """
  def decrement_followers(%Creator{} = creator) do
    new_count = max(0, creator.follower_count - 1)

    creator
    |> Creator.update_changeset(%{follower_count: new_count})
    |> Repo.update()
  end

  # ---------------------------------------------------------------------------
  # Status management
  # ---------------------------------------------------------------------------

  @doc """
  Deactivates a creator account.
  Deactivated creators cannot start new streams.
  """
  def deactivate_creator(%Creator{} = creator) do
    creator
    |> Creator.update_changeset(%{is_active: false})
    |> Repo.update()
  end


  # ---------------------------------------------------------------------------
  # Invite key management
  # ---------------------------------------------------------------------------

  @doc """
  Generates a fresh invite key for a creator.
  Called on creator creation and after every accepted invite.
  """
  def generate_invite_key do
    :crypto.strong_rand_bytes(12)
    |> Base.encode16(case: :lower)
  end

  @doc """
  Looks up a creator by their invite_key.
  Returns the creator or nil if not found.
  """
  def get_creator_by_invite_key(invite_key) do
    Repo.get_by(Creator, invite_key: invite_key)
  end

  @doc """
  Refreshes a creator's invite_key — called immediately after a guest accepts an invite.
  The old key is invalidated the moment the new one is written.
  Returns {:ok, creator} or {:error, changeset}.
  """
  def refresh_invite_key(creator_id) do
    case Repo.get(Creator, creator_id) do
      nil ->
        {:error, :not_found}

      creator ->
        creator
        |> Ecto.Changeset.change(%{invite_key: generate_invite_key()})
        |> Repo.update()
    end
  end
end
