defmodule Pod.Creators do
  @moduledoc """
  The Creators context.

  Handles everything around creator profiles — creation, updates, lookups,
  and follower counts. A Creator is linked one-to-one with a User account.
  Every broadcaster on the platform is a Creator.
  """

  import Ecto.Query
  alias Pod.Repo
  alias Pod.Stream.Creator

  # ---------------------------------------------------------------------------
  # Creating and updating creators
  # ---------------------------------------------------------------------------

  @doc """
  Creates a creator profile for an existing user.

  A user must have a creator profile to schedule or broadcast streams.
  The channel_id is auto-generated by the changeset — no need to pass it.
  """
  def create_creator(attrs) do
    %Creator{}
    |> Creator.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a creator's profile details — name, avatar, bio.
  """
  def update_creator(%Creator{} = creator, attrs) do
    creator
    |> Creator.update_changeset(attrs)
    |> Repo.update()
  end

  # ---------------------------------------------------------------------------
  # Fetching creators
  # ---------------------------------------------------------------------------

  @doc """
  Gets a creator by their ID.
  """
  def get_creator(id), do: Repo.get(Creator, id)

  @doc """
  Gets a creator by their ID, raising if not found.
  """
  def get_creator!(id), do: Repo.get!(Creator, id)

  @doc """
  Gets a creator by their user_id.

  Used after login to load the creator profile associated with the
  authenticated user account.
  """
  def get_creator_by_user(user_id) do
    Repo.get_by(Creator, user_id: user_id)
  end

  @doc """
  Gets a creator by their channel_id.

  channel_id is the public-facing identifier used in URLs and the RTMP path.
  e.g. rtmp://yourserver/live/{channel_id}/{stream_key}
  """
  def get_creator_by_channel(channel_id) do
    Repo.get_by(Creator, channel_id: channel_id)
  end

  @doc """
  Checks whether a user already has a creator profile.
  Used during onboarding to avoid duplicate creator records.
  """
  def creator_exists_for_user?(user_id) do
    Creator
    |> where([c], c.user_id == ^user_id)
    |> Repo.exists?()
  end

  @doc """
  Gets a creator with their live streams preloaded.
  Useful for public profile pages.
  """
  def get_creator_with_streams(id) do
    Creator
    |> where([c], c.id == ^id)
    |> preload(:live_streams)
    |> Repo.one()
  end

  # ---------------------------------------------------------------------------
  # Follower management
  # ---------------------------------------------------------------------------

  @doc """
  Increments the follower count for a creator by 1.
  Called when a user follows the creator.
  """
  def increment_followers(%Creator{} = creator) do
    creator
    |> Creator.update_changeset(%{follower_count: creator.follower_count + 1})
    |> Repo.update()
  end

  @doc """
  Decrements the follower count for a creator by 1.
  Guards against going below zero.
  """
  def decrement_followers(%Creator{} = creator) do
    new_count = max(0, creator.follower_count - 1)

    creator
    |> Creator.update_changeset(%{follower_count: new_count})
    |> Repo.update()
  end

  # ---------------------------------------------------------------------------
  # Status management
  # ---------------------------------------------------------------------------

  @doc """
  Deactivates a creator account.
  Deactivated creators cannot start new streams.
  """
  def deactivate_creator(%Creator{} = creator) do
    creator
    |> Creator.update_changeset(%{is_active: false})
    |> Repo.update()
  end
end
